import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Portfolio.module.css'
import { Card, Button } from 'react-bootstrap'



const Portfolio: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Christopher Kapic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar/>

      <div className={styles.portfolio}>
        <h1 style={{color: "#eeeeee"}}>Portfolio</h1>
        <div>

        <Card style={{ width: '18rem' }}>
          <Card.Img variant="top" src="" />
          <Card.Body>
            <Card.Title>GoLec</Card.Title>
            <Card.Text>
              Some quick example text to build on the card title and make up the bulk of
              the card's content.
            </Card.Text>
            <Button variant="primary">Check it out!</Button>
          </Card.Body>
        </Card>
        </div>
      </div>


      
    </div>
  )
}

export default Portfolio
