import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import profilePic from '../public/prof_neon.png'
import styles from '../styles/Home.module.css'



const Portfolio: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Christopher Kapic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar/>

      <div className={styles.hero}> {/* Hero Section */}
        <div style={{width: 256, height: 270, paddingBottom: 14, minHeight: 270}}>
          <Image src={profilePic} alt="Picture of Christopher Kapic" height={256} width={256}/>
        </div>
        <h1>Christopher Kapic</h1>
        <h4>Portfolio</h4>
        <p>Coming soon...</p>
        
      </div>

      
    </div>
  )
}

export default Portfolio
